"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowRight, Check, CheckCircle2, ChevronRight, Circle, FileCheck2, FileImage, FileText, ImagePlus, Info, LoaderCircle, LockKeyhole, RotateCcw, ScanLine, ShieldCheck, Upload, X, CircleAlert, Sparkles, Zap, Wand2, BadgeCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogTrigger, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { InstallAppButton } from '@/components/install-app-button';
import { defaults, parseRequirements, sizeLabel, type Rules, type Format } from '@/lib/requirements';
import { inspectFile, prepareFile, sampleFile, type Source, type Result } from '@/lib/file-engine';

function fileReadError(error: unknown): string {
 const name=error instanceof DOMException?error.name:'';
 if(name==='NotReadableError'||name==='NotFoundError')return 'Your browser could not keep access to that file. Move a copy to Downloads or Desktop, wait for cloud sync to finish, then choose it again.';
 return error instanceof Error?error.message:'Could not read this file. Try a smaller JPG, PNG, WebP, or PDF.';
}

async function memoryFile(file:File):Promise<File>{
 const bytes=await file.arrayBuffer();
 return new File([bytes],file.name,{type:file.type,lastModified:file.lastModified});
}

export default function Home(){
 const [source,setSource]=useState<Source|null>(null);const [result,setResult]=useState<Result|null>(null);const [rules,setRules]=useState<Rules>({...defaults});const [text,setText]=useState('');const [warnings,setWarnings]=useState<string[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [drag,setDrag]=useState(false);const [tab,setTab]=useState('original');const [sample,setSample]=useState(false);const [parsed,setParsed]=useState('');const [explanation,setExplanation]=useState('');const [help,setHelp]=useState<{title:string;text:string}[]>([]);
 const input=useRef<HTMLInputElement>(null);const screenshot=useRef<HTMLInputElement>(null);const seq=useRef(0);const active=useRef(false);const sourceRef=useRef<Source|null>(null);const resultRef=useRef<Result|null>(null);
 const releaseResult=(r:Result|null)=>{if(r){URL.revokeObjectURL(r.url);if(r.preview.startsWith('blob:'))URL.revokeObjectURL(r.preview);}};
 useEffect(()=>{const incoming=new URLSearchParams(window.location.search).get('requirements');if(incoming&&!text)setText(incoming.slice(0,6000));},[]);
 useEffect(()=>{sourceRef.current=source;},[source]);useEffect(()=>{resultRef.current=result;},[result]);
 useEffect(()=>()=>{seq.current++;if(sourceRef.current)URL.revokeObjectURL(sourceRef.current.url);releaseResult(resultRef.current);},[]);
 function clearResult(){seq.current++;releaseResult(result);setResult(null);setTab('original');setError('');setHelp([]);setExplanation('');}
 function update<K extends keyof Rules>(k:K,v:Rules[K]){clearResult();setRules(r=>({...r,[k]:v}));}
 async function load(file:File,isSample=false){if(active.current)return;active.current=true;const job=++seq.current;setBusy('Reading your file…');setError('');setHelp([]);setExplanation('');try{const stable=await memoryFile(file);const s=await inspectFile(stable);if(job!==seq.current){URL.revokeObjectURL(s.url);return;}if(source)URL.revokeObjectURL(source.url);releaseResult(result);setSource(s);setResult(null);setTab('original');setSample(isSample);if(s.isPdf)setRules(r=>({...r,format:'pdf',width:0,height:0}));}catch(e){setError(fileReadError(e));}finally{setBusy('');active.current=false;if(input.current)input.current.value='';}}
 async function demo(){try{await load(await sampleFile(),true);}catch{setError('Could not create the sample in this browser. Upload your own file instead.');}}
 function reset(){if(active.current)return;clearResult();if(source)URL.revokeObjectURL(source.url);setSource(null);setSample(false);setWarnings([]);setParsed('');setText('');setRules({...defaults});}
 function applyText(value=text){clearResult();const p=parseRequirements(value);setRules({...defaults,...p.rules,format:source?.isPdf?'pdf':p.rules.format||defaults.format});setWarnings(source?.isPdf&&p.rules.format&&p.rules.format!=='pdf'?[...p.warnings,'The text asks for an image, but your input is a PDF. This version keeps all PDF pages; choose an image input for image output.']:p.warnings);setParsed(p.found.length?`Read ${p.found.join(', ')}. Confirm the fields below.`:'Set the requirements below.');}
 async function ocr(file:File){if(active.current)return;active.current=true;setError('');setBusy('Loading screenshot reader…');let worker:any;try{if(file.size>10000000)throw new Error('Use a screenshot smaller than 10 MB.');const {createWorker}=await import('tesseract.js');worker=await createWorker('eng',1,{workerPath:'/vendor/ocr/worker.min.js',corePath:'/vendor/ocr',langPath:'/vendor/ocr',workerBlobURL:false,logger:(m:any)=>{if(m.status==='recognizing text')setBusy(`Reading screenshot · ${Math.round(m.progress*100)}%`);}});const response=await worker.recognize(await memoryFile(file));const extracted=response.data.text.trim();if(!extracted)throw new Error('No text found. Use a clearer screenshot or paste the requirements.');setText(extracted);applyText(extracted);setWarnings(w=>['Text was read from an image. Double-check all numbers and units.',...w]);}catch(e){setError(fileReadError(e));}finally{if(worker)await worker.terminate();setBusy('');active.current=false;if(screenshot.current)screenshot.current.value='';}}
 async function run(){if(!source||active.current)return;active.current=true;setError('');setHelp([]);setExplanation('');const job=++seq.current;setBusy('Preparing your file…');releaseResult(result);setResult(null);try{const r=await prepareFile(source,rules,setBusy);if(job!==seq.current){releaseResult(r);return;}setResult(r);setTab('result');}catch(e){setError(e instanceof Error?e.message:'Conversion failed. Try a smaller file.');}finally{setBusy('');active.current=false;}}
 async function explain(){const query=[text,error,...(result?.notes||[])].join('\n');try{const res=await fetch('/api/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});if(!res.ok)throw new Error();const data=await res.json() as {sources?:{title:string;text:string}[];explanation?:string|null};setHelp(data.sources||[]);setExplanation(data.explanation||'');}catch{setError('Help could not load. You can still adjust the requirements manually.');}}
 const passed=!!result&&result.checks.every(c=>c.pass);const isBusy=!!busy;const preview=tab==='result'&&result?result.preview:source?.preview;const imageOutput=!!result&&rules.format!=='pdf';
 return <div className="app-shell">
  <header className="topbar"><a href="/" className="brand" aria-label="FormFit home"><span className="brand-icon"><FileCheck2 size={25}/></span><span>FormFit</span><small>UPLOAD STUDIO</small></a><nav className="top-nav" aria-label="Primary"><a href="#workspace" className="top-nav-active">Workspace</a><a href="#why-formfit" className="top-nav-why">Why FormFit</a><a href="https://github.com/pragya238/formfit/blob/main/extension/README.md" target="_blank" rel="noreferrer">Use as extension ↗</a></nav><div className="top-note"><span className="privacy-pulse"/><LockKeyhole size={15}/><span>Your files stay on this device</span></div></header>
  <main>
   <div className="intro"><div><div className="eyebrow"><span className="eyebrow-dot"/> The last step before submit</div><h1>Make your next upload <em>fit.</em></h1><p>The right format. The right size. One less thing in your way.</p><p className="extension-note">Working on a form in Chrome? <a href="https://github.com/pragya238/formfit/tree/main/extension" target="_blank" rel="noreferrer">Use FormFit as an extension ↗</a></p></div><div className="intro-side"><div className="mini-stat"><strong>3</strong><span>checks before<br/>you download</span></div><div className="mini-stat"><strong>0</strong><span>files sent<br/>to a server</span></div><Button variant="outline" className="intro-action" disabled={isBusy} onClick={demo}><FileText size={15}/>Try a sample<ArrowRight size={15}/></Button><InstallAppButton/></div></div>
   <div className="workflow-rail" aria-label="FormFit workflow"><div className="workflow-item active"><span>01</span><div><b>Bring a file</b><small>Image or PDF</small></div></div><div className="workflow-line"/><div className={`workflow-item ${source?'active':''}`}><span>02</span><div><b>Set the brief</b><small>Read the form</small></div></div><div className="workflow-line"/><div className={`workflow-item ${result?'active':''}`}><span>03</span><div><b>Check & download</b><small>Only when it fits</small></div></div><div className="workflow-caption"><Sparkles size={14}/> Local-first by design</div></div>
   <div className="workspace" id="workspace">
    <div className="controls">
     <section className="panel panel-file"><div className="panel-heading"><span className="step">01</span><div><h2>Your file</h2><span className="panel-subtitle">The thing you need to submit</span></div><span className="meta">Up to 25 MB</span></div>
      <input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>e.target.files?.[0]&&load(e.target.files[0])}/>
      {!source?<button disabled={isBusy} className={`dropzone ${drag?'dragging':''}`} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files[0])load(e.dataTransfer.files[0]);}}><Upload size={28} className="upload-icon"/><strong>Drop your file here, or browse</strong><span>JPG, PNG, WebP, or PDF</span></button>:<><div className="file-row"><span className="file-icon">{source.isPdf?<FileText size={24}/>:<FileImage size={24}/>}</span><div className="file-info"><span className="filename">{source.file.name}</span><span className="meta">{sizeLabel(source.file.size)} · {source.isPdf?`${source.pages} page${source.pages===1?'':'s'}`:`${source.width} × ${source.height} px`}</span></div>{sample&&<span className="sample-chip">SAMPLE</span>}<Button variant="ghost" size="icon" aria-label="Remove file" disabled={isBusy} onClick={reset}><X size={17}/></Button></div><div className="comparison-stats"><Button variant="link" className="reset" disabled={isBusy} onClick={()=>input.current?.click()}>Choose another file</Button></div></>}
      <div className="privacy"><ShieldCheck size={13}/><span>Processed in your browser. No file uploads or sign-up.</span></div>
     </section>
     <section className="panel panel-brief"><div className="panel-heading"><span className="step">02</span><div><h2>What does the form need?</h2><span className="panel-subtitle">Paste the brief. FormFit handles the boring bits.</span></div><span className="ai-mark"><Wand2 size={13}/> smart read</span></div>
      <label htmlFor="requirements" className="sr-only">Paste upload requirements</label><textarea id="requirements" className="requirements-text" disabled={isBusy} value={text} maxLength={6000} onChange={e=>{setText(e.target.value);setParsed('');setWarnings([]);clearResult();}} placeholder={'Paste the instructions here…\nFor example: JPG, under 200 KB, 600 × 800 pixels.'}/>
      <div className="parse-actions"><Button variant="outline" size="sm" disabled={isBusy||!text.trim()} onClick={()=>applyText()}><ScanLine size={15}/>Read requirements</Button><Button className="ocr-label" variant="ghost" size="sm" disabled={isBusy} onClick={()=>screenshot.current?.click()}><ImagePlus size={15}/>From screenshot</Button></div><input hidden ref={screenshot} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&ocr(e.target.files[0])}/>
      {parsed&&<p className="small-copy" style={{marginBottom:12}} role="status">{parsed}</p>}{warnings.length>0&&<div className="notice">{warnings.map((w,i)=><p key={i}>{w}</p>)}</div>}
      <div className="fields">
       <div className="field"><label htmlFor="format">Output format</label><Select value={rules.format} disabled={isBusy||!!source?.isPdf} onValueChange={v=>update('format',v as Format)}><SelectTrigger id="format"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="jpeg">JPG</SelectItem><SelectItem value="png">PNG</SelectItem><SelectItem value="webp">WebP</SelectItem><SelectItem value="pdf">PDF</SelectItem></SelectContent></Select></div>
       <div className="field"><label htmlFor="max">Maximum size · KB</label><input id="max" type="number" min="1" max="50000" step="1" disabled={isBusy} value={rules.maxKB||''} onChange={e=>update('maxKB',Number(e.target.value))}/></div>
       {!source?.isPdf&&<><div className="field"><label htmlFor="width">Width · px</label><input id="width" type="number" min="1" max="8000" step="1" placeholder="Keep original" disabled={isBusy} value={rules.width||''} onChange={e=>update('width',Number(e.target.value))}/></div><div className="field"><label htmlFor="height">Height · px</label><input id="height" type="number" min="1" max="8000" step="1" placeholder="Keep original" disabled={isBusy} value={rules.height||''} onChange={e=>update('height',Number(e.target.value))}/></div></>}
       <div className="field"><label htmlFor="minimum">Minimum size · KB</label><input id="minimum" type="number" min="0" max="50000" step="1" placeholder="No minimum" disabled={isBusy} value={rules.minKB||''} onChange={e=>update('minKB',Number(e.target.value))}/></div>
       <div className="field"><label htmlFor="fit">{source?.isPdf?'PDF compression':'When proportions differ'}</label>{source?.isPdf?<Select value={rules.pdfMode} disabled={isBusy} onValueChange={v=>update('pdfMode',v as Rules['pdfMode'])}><SelectTrigger id="fit"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="preserve">Preserve text</SelectItem><SelectItem value="flatten">Convert pages to images</SelectItem></SelectContent></Select>:<Select value={rules.fit} disabled={isBusy} onValueChange={v=>update('fit',v as Rules['fit'])}><SelectTrigger id="fit"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="contain">Fit with white padding</SelectItem><SelectItem value="cover">Crop from center</SelectItem></SelectContent></Select>}</div>
      </div>
      <p className="small-copy">1 KB = 1,000 bytes. Blank dimensions preserve proportions; size targets may require downscaling.</p>
      <div className="rule-strip"><span><BadgeCheck size={14}/> You stay in control</span><span><Zap size={14}/> No quality guessing</span><span><LockKeyhole size={14}/> Private by default</span></div>
      {source?.isPdf&&rules.pdfMode==='flatten'&&<div className="notice" style={{marginTop:12}}>Image-based compression removes selectable text, links, fillable fields, and signatures. Choose Preserve text when these matter.</div>}
      {isBusy&&<div className="busy-line" role="status"><LoaderCircle size={15} className="spin"/>{busy}</div>}
      {error&&<div className="notice error" style={{marginTop:12}} role="alert">{error}</div>}
      <Button className="prepare" disabled={!source||isBusy} onClick={run}>{isBusy?<LoaderCircle className="spin" size={18}/>:<FileCheck2 size={18}/>} {isBusy?'Working on it…':'Prepare my file'}{!isBusy&&<ArrowRight size={17}/>}</Button>
     </section>
    </div>
    <section className="panel preview-panel" aria-label="File preview and verification"><div className="preview-header"><div><span className="preview-kicker">YOUR OUTPUT, BEFORE THE FORM SEES IT</span><h2>Preview & check</h2></div><Tabs className="tabset" value={tab} onValueChange={setTab}><TabsList aria-label="Preview version"><TabsTrigger value="original">Original</TabsTrigger><TabsTrigger value="result" disabled={!result}>Result</TabsTrigger></TabsList></Tabs></div>
     <div className="preview-stage">{preview?<><img src={preview} alt={tab==='result'?'Converted file preview':'Original file preview'}/><span className="stage-tag">{(tab==='original'&&source?.isPdf)||(tab==='result'&&rules.format==='pdf')?'PAGE 1 PREVIEW':tab==='result'&&result?`${result.width} × ${result.height} PX`:'ORIGINAL'}</span></>:<div className="preview-empty"><FileCheck2 size={48}/><h3>A little smaller.<br/>Ready for the next step.</h3><p>Add a file to see your preview and upload checks here.</p></div>}</div>
     <div className="check-section"><div className="check-title"><h3>Upload checklist</h3><span className={`status ${result?(passed?'success':'warning'):''}`}>{result?(passed?'Checks passed':'Needs adjustment'):'Waiting for file'}</span></div>
      {result?<div aria-live="polite">{result.checks.map(c=><div className="check-row" key={c.label}>{c.pass?<CheckCircle2 size={16} className="pass-icon"/>:<CircleAlert size={16} className="fail-icon"/>}<span>{c.label}</span><span className="check-detail">{c.detail}</span></div>)}<div className="check-row"><Info size={16} className="check-muted"/><span>Readability & appearance</span><span className="check-detail">Review the preview</span></div></div>:<div className="receipt-placeholder">{[['File format',rules.format==='jpeg'?'JPG':rules.format.toUpperCase()],['File size',`≤ ${sizeLabel(rules.maxKB*1000)}`],['Dimensions',rules.width||rules.height?`${rules.width||'Auto'} × ${rules.height||'Auto'} px`:'Keep proportions']].map(([a,b])=><div className="check-row" key={a}><Circle size={15} className="check-muted"/><span>{a}</span><span className="check-detail">{b}</span></div>)}</div>}
      {result?.notes.length? <div className="notice" style={{marginTop:15}}>{result.notes.map((n,i)=><p key={i}>{n}</p>)}</div>:null}
      <div className="download-box">{result&&source&&<div className="result-stats"><span>{sizeLabel(source.file.size)} <span aria-hidden="true">→</span> <b>{sizeLabel(result.blob.size)}</b></span><span>{result.blob.size<source.file.size?`${Math.round((1-result.blob.size/source.file.size)*100)}% smaller`:'Reformatted'}</span></div>}
       {passed&&result?<Button asChild className="download"><a href={result.url} download={result.name}><ArrowDownToLine size={18}/>Download {rules.format==='jpeg'?'JPG':rules.format.toUpperCase()}</a></Button>:<Button className="download" disabled><ArrowDownToLine size={18}/>Download prepared file</Button>}
       <p className="result-caption">{result?'Verified against your settings. Final acceptance is up to the form.':'Your download will be ready after the checks pass.'}</p>
       {result&&<a className="zoom-link" href={rules.format==='pdf'?result.url:result.preview} target="_blank" rel="noreferrer">{rules.format==='pdf'?'Open the full PDF to inspect every page':'Open the result at full size'}</a>}
      </div>
      {result&&!passed&&<Button variant="link" size="sm" onClick={explain} style={{marginTop:8}}>Help me understand the mismatch<ChevronRight size={14}/></Button>}
      {explanation&&<p className="info-content">{explanation}</p>}{help.length>0&&<div className="info-content">{help.map((h,i)=><p key={i}><b>{h.title}</b><br/>{h.text}</p>)}</div>}
     </div>
    </section>
   </div>
   <section className="why-section" id="why-formfit" aria-labelledby="why-title">
    <div className="why-heading"><div><span className="preview-kicker">ONE WORKFLOW, THREE WAYS TO USE IT</span><h2 id="why-title">Why FormFit?</h2><p>Upload rules are often buried in long forms. FormFit turns them into a clear, local checklist before you submit.</p></div><a className="why-link" href="https://github.com/pragya238/formfit/blob/main/extension/README.md" target="_blank" rel="noreferrer">Get the extension ↗</a></div>
    <div className="usage-grid">
     <article className="usage-card"><span className="usage-number">01</span><h3>Browser</h3><p>Open FormFit in Chrome, Edge, Safari, or Firefox. Choose an image or PDF, paste the form’s requirements, then download the verified result.</p><span className="usage-tip">Best for a one-off upload</span></article>
     <article className="usage-card"><span className="usage-number">02</span><h3>App</h3><p>Install FormFit from the browser’s install icon or the “Install FormFit” button. Launch it from your desktop, Start menu, or home screen like a normal app.</p><span className="usage-tip">Same private workflow, no tab hunting</span></article>
     <article className="usage-card"><span className="usage-number">03</span><h3>Extension</h3><p>In Chrome or Edge, open Extensions, enable Developer mode, choose “Load unpacked,” and select the repository’s <code>extension</code> folder. Pin FormFit Companion to scan an upload page.</p><span className="usage-tip">Best when a website hides its limits</span></article>
    </div>
    <p className="why-footnote"><LockKeyhole size={14}/> Processing stays on this device in every mode. Android works through the browser or installed app; the extension is for desktop Chrome and Edge.</p>
   </section>
  </main>
  <footer className="footer"><span>Small files. Less friction.</span><div className="inline-row"><Dialog><DialogTrigger asChild><button>How it works & limitations</button></DialogTrigger><DialogContent><DialogTitle>Know what’s being checked.</DialogTitle><DialogDescription>FormFit checks the requirements you confirm before conversion.</DialogDescription><div className="info-content"><p><b>Your files stay here.</b> Conversion and screenshot text recognition happen in your browser. Files are not sent to a server. Closing or refreshing this page clears your working files.</p><p><b>Read, then confirm.</b> Screenshot reading uses OCR; pasted requirements use a rules-based parser. Both can miss context. Review the detected numbers, units, format, and crop mode before preparing.</p><p><b>Checks have limits.</b> File type, byte size, image dimensions, and PDF page count are checked. Readability, identity-photo rules, background colour, DPI metadata, and a website’s final acceptance are not certified.</p><p><b>PDF trade-offs.</b> Preserve text mode optimizes structure. Convert pages to images can reduce scanned PDFs, but removes document features and can reduce text quality. PDFs stay PDF; this version does not extract individual pages.</p><p><b>Help requests.</b> Clicking the mismatch help button sends the requirement text and error details, but no file, to retrieve relevant help notes.</p></div></DialogContent></Dialog><Button variant="ghost" size="sm" className="reset" disabled={isBusy} onClick={reset}><RotateCcw size={13}/>Start over</Button></div></footer>
 </div>
}
