import {type Rules, type Check, dimensions, validateRules, checkOutput} from './requirements';
export type Source={file:File;url:string;preview:string;width:number;height:number;pages:number;isPdf:boolean};
export type Result={blob:Blob;url:string;preview:string;width:number;height:number;checks:Check[];notes:string[];name:string;pages:number};
export async function loadImage(blob:Blob):Promise<HTMLImageElement>{const url=URL.createObjectURL(blob);try{return await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('This image could not be read. Try a JPG, PNG, or WebP file.'));im.src=url;});}finally{URL.revokeObjectURL(url);}}
export function canvasBlob(canvas:HTMLCanvasElement,type:string,quality=.94):Promise<Blob>{return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Your browser could not encode this file. Try a smaller image.')),type,quality));}
async function openPdf(file:Blob){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdf.worker.min.mjs';return pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),useSystemFonts:true}).promise;}
async function renderPage(page:any,scale:number){const vp=page.getViewport({scale});if(vp.width*vp.height>16000000)throw new Error('This PDF page is too large to render safely.');const canvas=document.createElement('canvas');canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);const ctx=canvas.getContext('2d')!;await page.render({canvas,canvasContext:ctx,viewport:vp,background:'rgb(255,255,255)'}).promise;return canvas;}
export async function inspectFile(file:File):Promise<Source>{
 if(file.size>25000000)throw new Error('Choose a file smaller than 25 MB.');if(file.size===0)throw new Error('This file is empty. Choose another file.');
 const header=new Uint8Array(await file.slice(0,12).arrayBuffer());const isPdf=new TextDecoder().decode(header).startsWith('%PDF-');
 if(isPdf){const pdf=await openPdf(file);try{if(pdf.numPages>20)throw new Error('This version supports PDFs up to 20 pages.');const p=await pdf.getPage(1);const vp=p.getViewport({scale:1});const canvas=await renderPage(p,Math.min(1.3,1000/Math.max(vp.width,vp.height)));const preview=canvas.toDataURL('image/jpeg',.85);return {file,url:URL.createObjectURL(file),preview,width:0,height:0,pages:pdf.numPages,isPdf:true};}finally{await pdf.loadingTask.destroy();}}
 const jpg=header[0]===255&&header[1]===216;const png=header[0]===137&&header[1]===80&&header[2]===78&&header[3]===71;const webp=new TextDecoder().decode(header.slice(0,4))==='RIFF'&&new TextDecoder().decode(header.slice(8,12))==='WEBP';if(!jpg&&!png&&!webp)throw new Error('Supported files: JPG, PNG, WebP, and PDF. HEIC, SVG, and animated formats are not supported yet.');
 const im=await loadImage(file);if(im.naturalWidth*im.naturalHeight>40000000)throw new Error('Choose an image below 40 megapixels.');const url=URL.createObjectURL(file);return {file,url,preview:url,width:im.naturalWidth,height:im.naturalHeight,pages:1,isPdf:false};
}
function draw(im:HTMLImageElement,w:number,h:number,fit:Rules['fit']){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';const scale=fit==='cover'?Math.max(w/im.naturalWidth,h/im.naturalHeight):Math.min(w/im.naturalWidth,h/im.naturalHeight);const dw=im.naturalWidth*scale,dh=im.naturalHeight*scale;ctx.drawImage(im,(w-dw)/2,(h-dh)/2,dw,dh);return c;}
async function bestImage(c:HTMLCanvasElement,type:string,max:number){let high=await canvasBlob(c,type,.98);if(high.type!==type)throw new Error('Your browser does not support this output format. Choose JPG or PNG.');if(high.size<=max||type==='image/png')return high;let low=.18,hi=.98,best=await canvasBlob(c,type,low);if(best.size>max)return best;for(let i=0;i<8;i++){const q=(low+hi)/2;const b=await canvasBlob(c,type,q);if(b.size<=max){best=b;low=q;}else hi=q;}return best;}
export async function prepareFile(source:Source,r:Rules,onProgress:(s:string)=>void):Promise<Result>{
 validateRules(r);const notes:string[]=[];let blob:Blob;let preview=source.preview;let width=0,height=0;const max=Math.floor(r.maxKB*1000);let pages=source.pages;
 if(source.isPdf){if(r.format!=='pdf')throw new Error('PDF inputs stay PDF so every page is preserved. Choose PDF output.');
 const {PDFDocument}=await import('pdf-lib');
 if(r.pdfMode==='preserve'){onProgress('Optimizing the PDF structure…');const doc=await PDFDocument.load(await source.file.arrayBuffer());const bytes=await doc.save({useObjectStreams:true});blob=new Blob([new Uint8Array(bytes)],{type:'application/pdf'});if(source.file.size<blob.size)blob=new Blob([await source.file.arrayBuffer()],{type:'application/pdf'});notes.push('All pages retained. Text and document structure preserved; scanned images are not recompressed in this mode.');}
 else {notes.push('Pages were converted to images. Selectable text, links, forms, accessibility tags, and signatures are not preserved. Inspect every page for readability.');const pdf=await openPdf(source.file);try{if(pdf.numPages>10)throw new Error('Image-based PDF compression supports up to 10 pages. Use Preserve text for larger documents.');blob=new Blob([]);for(const [scale,q] of [[1.5,.85],[1.15,.65],[.85,.45]]){const doc=await PDFDocument.create();for(let i=1;i<=pdf.numPages;i++){onProgress(`Compressing PDF · page ${i} of ${pdf.numPages}…`);const page=await pdf.getPage(i);const vp=page.getViewport({scale:1});const canvas=await renderPage(page,Math.min(scale,1800/Math.max(vp.width,vp.height)));const jpg=await canvasBlob(canvas,'image/jpeg',q);const embedded=await doc.embedJpg(await jpg.arrayBuffer());const out=doc.addPage([vp.width,vp.height]);out.drawImage(embedded,{x:0,y:0,width:vp.width,height:vp.height});canvas.width=0;canvas.height=0;page.cleanup();}const bytes=await doc.save();blob=new Blob([new Uint8Array(bytes)],{type:'application/pdf'});if(blob.size<=max)break;}}finally{await pdf.loadingTask.destroy();}}
 const verification=await PDFDocument.load(await blob!.arrayBuffer());pages=verification.getPageCount();if(pages!==source.pages)throw new Error('Page count changed. Conversion stopped to protect your document.');const pd=await openPdf(blob!);try{const page=await pd.getPage(1);const vp=page.getViewport({scale:1});preview=(await renderPage(page,Math.min(1.3,1000/Math.max(vp.width,vp.height)))).toDataURL('image/jpeg',.85);}finally{await pd.loadingTask.destroy();}
 if(r.width||r.height)notes.push('Pixel dimensions do not apply to PDF output.');
 }else{
 onProgress('Resizing and finding the best quality…');const im=await loadImage(source.file);const d=dimensions(source.width,source.height,r);width=d.width;height=d.height;let canvas=draw(im,width,height,r.fit);
 if(width>source.width||height>source.height)notes.push('The image was enlarged. Added pixels do not restore detail.');if(r.width&&r.height){if(r.fit==='cover')notes.push('The image was center-cropped to fill the target dimensions. Check that all important content is visible.');else if(Math.abs(source.width/source.height-width/height)>.01)notes.push('White padding was added to fit the dimensions without cropping.');}
 if(r.format==='pdf'){const {PDFDocument}=await import('pdf-lib');let out:Blob=new Blob([]);for(const q of [.95,.8,.6,.4,.2]){const jpg=await canvasBlob(canvas,'image/jpeg',q);const doc=await PDFDocument.create();const img=await doc.embedJpg(await jpg.arrayBuffer());const page=doc.addPage([width*.75,height*.75]);page.drawImage(img,{x:0,y:0,width:width*.75,height:height*.75});out=new Blob([new Uint8Array(await doc.save())],{type:'application/pdf'});if(out.size<=max)break;}blob=out;preview=canvas.toDataURL('image/jpeg',.85);pages=1;notes.push('Created a single-page PDF from your image. Pixel dimensions are not verified for PDF output.');}
 else {const type=`image/${r.format}`;blob=await bestImage(canvas,type,max);if(!r.width&&!r.height){for(let i=0;blob.size>max&&i<12&&width>64&&height>64;i++){const f=Math.max(.5,Math.min(.88,Math.sqrt(max/blob.size)*.92));width=Math.max(1,Math.floor(width*f));height=Math.max(1,Math.floor(height*f));canvas=draw(im,width,height,r.fit);blob=await bestImage(canvas,type,max);}if(width!==d.width||height!==d.height)notes.push('Dimensions were reduced to meet the size limit. Check small text before uploading.');}const verified=await loadImage(blob);width=verified.naturalWidth;height=verified.naturalHeight;preview=URL.createObjectURL(blob);}
 }
 const checks=checkOutput(blob!.size,blob!.type,width,height,r,r.format==='pdf');if(source.isPdf)checks.push({label:'Page count',detail:`${pages} of ${source.pages} pages`,pass:pages===source.pages});
 if(blob!.size>max)notes.push('This target could not be met. Try a larger size limit, smaller dimensions, JPG output, or image-based PDF compression.');if(r.minKB&&blob!.size<r.minKB*1000)notes.push('The result is smaller than the minimum. Increase dimensions or choose a less compressed format. Artificial padding is not added.');
 const name=source.file.name.replace(/\.[^.]+$/,'')+'-formfit.'+(r.format==='jpeg'?'jpg':r.format);
 return {blob:blob!,url:URL.createObjectURL(blob!),preview,width,height,checks,notes,name,pages};
}
export async function sampleFile(){const c=document.createElement('canvas');c.width=1400;c.height=1800;const x=c.getContext('2d')!;x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#25312d';x.font='bold 72px Arial';x.fillText('A small file.',130,230);x.fillText('A smoother upload.',130,325);x.fillStyle='#c44421';x.fillRect(130,405,110,8);x.fillStyle='#656d79';x.font='32px Arial';x.fillText('FORMFIT / SAMPLE DOCUMENT',130,515);x.fillStyle='#25312d';x.font='28px Arial';['Use this sample to try the converter.','Every line should stay readable.','','Original: 1400 × 1800 pixels','Try: JPG, under 200 KB','','No personal information.','No account numbers.','Just a useful little test.'].forEach((s,i)=>x.fillText(s,130,665+i*68));x.strokeStyle='#dfe2e7';x.beginPath();x.moveTo(130,1440);x.lineTo(1270,1440);x.stroke();x.font='24px Arial';x.fillStyle='#656d79';x.fillText('Check the preview before your next upload.',130,1510);return new File([await canvasBlob(c,'image/png')],'sample-document.png',{type:'image/png'});}
