// Original, application-specific guidance. No external documents are copied.
export const helpCorpus=[
 {id:'size',title:'When a file is still too large',text:'A size limit is measured in bytes. JPEG and WebP allow lossy compression; PNG does not use the same quality control. If dimensions are fixed, a target can be impossible at acceptable quality. Increase the allowed size, switch an accepted format, or lower dimensions when the form permits it.',tags:'size maximum large compression jpg jpeg png webp kb mb target'},
 {id:'dimensions',title:'Pixel dimensions and aspect ratio',text:'Width and height refer to pixels. Setting one dimension keeps the original proportions. Setting both requires padding or cropping when proportions differ. White padding preserves content; center cropping can remove important edges. Inspect the full-size result.',tags:'dimensions width height px pixel ratio crop cropping padding resize'},
 {id:'minimum',title:'When the file is below the minimum',text:'Some forms specify a minimum as well as a maximum. This app does not insert artificial padding. Try higher dimensions or a less compressed accepted format. Do not enlarge an image beyond what is necessary: extra pixels do not restore lost detail.',tags:'minimum small below range min'},
 {id:'pdf',title:'Two ways to compress a PDF',text:'Preserve text mode rewrites the PDF structure while retaining text and pages. It may barely shrink scanned pages. Image-based mode renders every page and recompresses it, removing selectable text, links, forms, signatures, and accessibility structure. Verify every page before use.',tags:'pdf scanned scan pages preserve text flatten large compression'},
 {id:'readability',title:'A passing size check is not a readability check',text:'Compression can blur small text and fine lines. Open the full-size output and check the smallest text, edges, and any required content. The app checks file format, byte size, image dimensions, and PDF page count; it cannot guarantee that a form will accept a file.',tags:'quality blurry readability legible text appearance acceptance'},
 {id:'units',title:'KB, pixels, and DPI',text:'FormFit uses decimal kilobytes: 1 KB equals 1,000 bytes. Its check is conservative for a limit stated in KiB. DPI describes physical print density, not pixel count. DPI metadata and physical dimensions are not certified by this version.',tags:'dpi ppi kb kib mb mib units cm mm inches physical pixels'}
];
const tokenize=(s:string):string[]=>s.toLowerCase().match(/[a-z]{3,}/g)||[];
export function retrieveHelp(query:string){const terms=new Set(tokenize(query));return helpCorpus.map(d=>{const tokens=tokenize(d.title+' '+d.text+' '+d.tags);let score=0;for(const term of terms){const count=tokens.filter(t=>t===term).length;const df=helpCorpus.filter(x=>tokenize(x.title+' '+x.text+' '+x.tags).includes(term)).length;score+=(count/(count+1.2))*Math.log(1+(helpCorpus.length-df+.5)/(df+.5));}return {...d,score};}).filter(d=>d.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(({id,title,text})=>({id,title,text}));}
