import assert from 'node:assert/strict';
import ts from 'typescript';
import fs from 'node:fs/promises';
const compile=async p=>{const src=await fs.readFile(p,'utf8');const js=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));};
const {parseRequirements,defaults,validateRules,dimensions,checkOutput}=await compile('lib/requirements.ts');
const {retrieveHelp}=await compile('lib/help-corpus.ts');
assert.deepEqual(parseRequirements('JPG, under 200 KB, 600 × 800 pixels').rules,{format:'jpeg',maxKB:200,width:600,height:800});
assert.deepEqual(parseRequirements('PNG between 20 KB and 200 KB').rules,{format:'png',minKB:20,maxKB:200});
assert.equal(parseRequirements('PDF less than 2 MB').rules.maxKB,2000);
assert.equal(parseRequirements('300 x 400 mm').rules.width,undefined);
assert.ok(parseRequirements('300 x 400 mm').warnings.length);
assert.ok(parseRequirements('JPEG or PNG, 300 DPI').warnings.length>=2);
assert.throws(()=>validateRules({...defaults,width:-1}));
assert.throws(()=>validateRules({...defaults,minKB:201}));
assert.throws(()=>validateRules({...defaults,width:8000,height:8000}));
assert.deepEqual(dimensions(1400,1800,{...defaults,width:700}),{width:700,height:900});
assert.equal(checkOutput(200001,'image/jpeg',600,800,{...defaults,width:600,height:800})[1].pass,false);
assert.equal(checkOutput(199000,'image/png',600,800,{...defaults,width:600,height:800})[0].pass,false);
assert.equal(checkOutput(10000,'image/jpeg',600,800,{...defaults,minKB:20})[2].pass,false);
assert.equal(retrieveHelp('PDF scanned pages flatten compression')[0].id,'pdf');
assert.equal(retrieveHelp('file smaller than minimum')[0].id,'minimum');
assert.equal(retrieveHelp('unrelatedzzzz').length,0);
console.log('16 core assertions passed: parsing, invalid limits, unit warnings, dimensions, exact byte checks, and help retrieval.');
